version: '3.8'

services:
  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - "80:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
